name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      ECR_REGISTRY: 260332828352.dkr.ecr.us-east-1.amazonaws.com/myrepo
      IMAGE_TAG: latest

    # steps:
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      - name: Build with dotnet
        run: dotnet build --configuration Release


      
      # - name: Checkout repository
      #   uses: actions/checkout@v2

      # - name: Dotnet Build
      #   run: |
      #     cd SampleWebApiAspNetCore
      #     dotnet build -c Release
      #   working-directory: ./SampleWebApiAspNetCore

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-build
          path: ./SampleWebApiAspNetCore/bin/Release/net7.0

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: ${{ env.ECR_REGISTRY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dotnet-build
          path: build-artifacts

      - name: Build Docker image
        run: |
          cd build-artifacts
          docker build -t $ECR_REGISTRY:$IMAGE_TAG .
          docker push $ECR_REGISTRY:$IMAGE_TAG
